name: S3 Auto Backup
description: Home Assistant Addon to automatically create backups and uploads them to aws s3
version: 1.1.1
slug: s3_auto_backup
init: false
hassio_api: true
hassio_role: backup
panel_icon: mdi:cloud-upload
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  cron: 0 3 1,15 * *
  logging: true
  delete_local_backup_after_upload: false

schema:
  access_key_id: password
  secret_access_key: password
  bucket_name: str
  cron: str
  logging: bool
  backup_password: password?
  delete_local_backup_after_upload: bool

map:
  - backup:rw

