name: S3 Auto Backup
description: Home Assistant Addon to automatically create backups and uploads them to aws s3
version: 1.1.0
slug: s3_auto_backup
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  logging: true
  cron: 0 3 1,15 * *

schema:
  access_key_id: password
  secret_access_key: password
  bucket_name: str
  cron: str
  logging: bool
  backup_password: password?

map:
  - backup:rw

hassio_api: true
hassio_role: admin
