name: S3 Auto Backup
description: Home Assistant Addon to automatically create backups and uploads them to aws s3
version: 1.0.1
slug: s3_auto_backup
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

hassio_api: true
