name: S3 Auto Backup
description: Home Assistant Addon to automatically create backups and uploads them to aws s3
version: 1.0.10
slug: s3_auto_backup
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  logging: true

schema:
  public_key: str
  secret_key: str
  bucket_name: str
  logging: bool

hassio_api: true
hassio_role: default